/**
 * @file Coriolis.h
 * @author Guy Burroughes
 * @brief 
 * @version 0.1
 * @date 2021-12-19
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#pragma once

#include "Utils.h"

/**
 * @brief Autogenerated Coriolis torque vector
 * 
 * @param q joint pose
 * @param qp joint velocity
 * @param C output coriolis torque
 */
void coriolis(const Eigen::Matrix<float, 7, 1> q,
              const Eigen::Matrix<float, 7, 1> qp,
              Eigen::Matrix<float, 7, 1> &C);