/**
 * @file MassMatrix.h
 * @author Guy Burrougehs
 * @brief 
 * @version 0.1
 * @date 2021-12-19
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#pragma once

#include "Utils.h"

/**
 * @brief Autogenerated function which calculates mass matrix for a position.
 *
 * @param q joint angles (degrees)
 * @param M Ouput Mass Matrix
 */
void mass_matrix(const Eigen::Matrix<float, 7, 1> q,
                 Eigen::Matrix<float, 7, 7> &M);